version: 2

build:
   os: ubuntu-22.04
   tools:
     python: "miniconda3-4.7"

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .

#conda:
 # environment: environment.yml

# Build PDF & ePub
formats:
  - epub
  - pdf