name: grail-env
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.12.14
  - libffi=3.4.2
  - liblzma=5.6.3
  - libsqlite=3.47.2
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.4.0
  - pip=24.3.1
  - python=3.10.16
  - readline=8.2
  - setuptools=75.6.0
  - tk=8.6.13
  - wheel=0.45.1
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.3.2
      - aizynthfinder==4.3.1
      - alabaster==1.0.0
      - alembic==1.14.0
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.7.0
      - appnope==0.1.4
      - apted==1.0.3
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.4
      - async-timeout==5.0.1
      - attrs==25.3.0
      - autopage==0.5.2
      - autopep8==2.3.1
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - biopython==1.85
      - black==24.10.0
      - bleach==6.2.0
      - blinker==1.9.0
      - blosc2==2.7.1
      - cachetools==5.5.2
      - certifi==2025.6.15
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.2.1
      - cliff==4.8.0
      - cmaes==0.11.1
      - cmd2==2.5.8
      - coloredlogs==15.0.1
      - colorlog==6.9.0
      - comm==0.2.2
      - commonmark==0.9.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - debugpy==1.8.11
      - decorator==5.1.1
      - defusedxml==0.7.1
      - deprecated==1.2.15
      - dill==0.3.9
      - docutils==0.21.2
      - entrypoints==0.4
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - faiss-cpu==1.9.0.post1
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - flake8==7.1.1
      - flatbuffers==24.12.23
      - fonttools==4.58.4
      - fqdn==1.5.1
      - frozenlist==1.7.0
      - fsspec==2025.5.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gnureadline==8.2.13
      - grpcio==1.68.1
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - humanfriendly==10.0
      - idna==3.10
      - imagesize==1.4.1
      - importlib-resources==6.5.2
      - iniconfig==2.0.0
      - ipykernel==6.29.5
      - ipython==8.31.0
      - ipython-genutils==0.2.0
      - ipywidgets==7.8.5
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.1
      - json5==0.10.0
      - jsonpickle==4.1.1
      - jsonpointer==3.0.0
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - jupyter==1.1.1
      - jupyter-client==7.4.9
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.11.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==1.1.11
      - jupytext==1.16.6
      - kiwisolver==1.4.8
      - latexify-py==0.4.4
      - lightning-utilities==0.11.9
      - llvmlite==0.43.0
      - loguru==0.7.3
      - mako==1.3.8
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - matplotlib-inline==0.1.7
      - mccabe==0.7.0
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - mistune==3.1.0
      - molbloom==2.1.1
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.5.0
      - multipledispatch==1.0.0
      - mypy==1.14.1
      - mypy-extensions==1.0.0
      - myst-parser==4.0.0
      - narwhals==1.43.0
      - nbclassic==1.1.0
      - nbclient==0.10.2
      - nbconvert==7.16.5
      - nbformat==5.10.4
      - nbsphinx==0.9.6
      - ndindex==1.9.2
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - notebook==6.5.7
      - notebook-shim==0.2.4
      - numba==0.60.0
      - numexpr==2.10.0
      - numpy==2.2.6
      - numpydoc==1.8.0
      - onnxruntime==1.16.3
      - optuna==2.10.1
      - optuna-fast-fanova==0.0.4
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.3.0
      - pandocfilters==1.5.1
      - paretoset==1.2.4
      - parso==0.8.4
      - pathspec==0.12.1
      - pbr==6.1.0
      - pep8==1.7.1
      - pexpect==4.9.0
      - pillow==11.2.1
      - platformdirs==4.3.6
      - plotly==6.1.0
      - pluggy==1.5.0
      - prettytable==3.12.0
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.48
      - propcache==0.3.2
      - protobuf==6.31.1
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==20.0.0
      - pycodestyle==2.12.1
      - pycparser==2.22
      - pydantic==2.10.4
      - pydantic-core==2.27.2
      - pydeck==0.9.1
      - pydeprecate==0.3.2
      - pyflakes==3.2.0
      - pygments==2.18.0
      - pymongo==3.13.0
      - pyparsing==3.2.3
      - pyperclip==1.9.0
      - pytest==8.3.4
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.2.1
      - pytorch-lightning==1.6.5.post0
      - pytorch-tree-lstm==0.1.3
      - pytz==2025.2
      - pyvis==0.3.2
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - rdchiral==1.1.0
      - rdkit==2024.9.6
      - rdkit-pypi==2022.9.5
      - recommonmark==0.7.1
      - referencing==0.36.2
      - requests==2.32.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - route-distances==1.2.1
      - rpds-py==0.25.1
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - seaborn==0.13.2
      - send2trash==1.8.3
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - snowballstemmer==2.2.0
      - soupsieve==2.6
      - sphinx==8.1.3
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - sqlalchemy==2.0.36
      - stack-data==0.6.3
      - stevedore==5.4.0
      - streamlit==1.45.1
      - sympy==1.14.0
      - tables==3.10.1
      - tabulate==0.9.0
      - tenacity==9.1.2
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - timeout-decorator==0.5.0
      - tinycss2==1.4.0
      - toml==0.10.2
      - tomli==2.2.1
      - torch==2.7.1
      - torch-geometric==2.6.1
      - torchmetrics==1.5.2
      - tornado==6.5.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.14.0
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.4.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - widgetsnbextension==3.6.10
      - wrapt==1.17.0
      - yapf==0.43.0
      - yarl==1.20.1
