#!/usr/bin/env python3
r"""The gap between what leaderboards publish and what they support, drawn as two ladders.

The paper reports two readings of "supported" and they are not the same ladder. One asks only that
no cell contradict the published order; the other asks each cell to separate the pair with an
interval. Stated as a list of numbers the two have been read as one, and the arithmetic then looks
wrong: $298-170$ is not $159+40$. Drawn as two tracks the question does not arise.

The figure also carries the paper's own deflation, which is its least flattering and most useful
result: of the places that a stricter reading removes, far more go to what a benchmark could never
resolve than to the conventions this paper is about.

Every number is read from results/places_decomposition.json. Nothing is retyped.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "paper" / "app" / "decomp_figure.tex"
ART = ROOT / "results" / "places_decomposition.json"

W = 10.4          # cm, the width one published place scale spans
BAR = 0.42        # cm, bar height
GAP = 0.72        # cm, between bars


def _code_version() -> dict:
    def _git(*a):
        try:
            return subprocess.run(["git", *a], cwd=ROOT, capture_output=True, text=True,
                                  timeout=10).stdout.strip() or None
        except Exception:
            return None
    return {"script": pathlib.Path(__file__).name, "git_commit": _git("rev-parse", "HEAD")}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(OUT))
    args = ap.parse_args()

    d = json.loads(ART.read_text())
    pub = d["places_published"]
    sign = d["supported_when_every_cell_agrees_in_sign"]
    own = d["supported_when_its_own_cell_separates"]
    every = d["supported_when_every_cell_separates"]
    power = d["lost_before_any_choice_is_varied"]
    grid = d["lost_to_the_grid"]
    assert pub - own == power and own - every == grid, "the ladder does not close"

    def x(n: int) -> float:
        return W * n / pub

    L = ["% generated by scripts/make_decomp_figure.py -- do not edit by hand",
         "\\begin{tikzpicture}[x=1cm, y=1cm, font=\\scriptsize]"]

    def bar(y, n, colour, label, note=None):
        # the full scale stays visible behind every bar, so each reading is read against the same
        # 298 rather than against the bar above it
        L.append(f"\\fill[gRule!8] (0,{y:.2f}) rectangle ({W:.3f},{y + BAR:.2f});")
        L.append(f"\\fill[{colour}] (0,{y:.2f}) rectangle ({x(n):.3f},{y + BAR:.2f});")
        L.append(f"\\node[anchor=east, {colour}] at (-0.12,{y + BAR / 2:.2f}) {{{label}}};")
        L.append(f"\\node[anchor=west, font=\\scriptsize\\bfseries, {colour}] "
                 f"at ({x(n) + 0.10:.3f},{y + BAR / 2:.2f}) {{{n}}};")
        if note:
            L.append(f"\\node[anchor=west, gRule!85] at ({x(n) + 0.62:.3f},{y + BAR / 2:.2f}) "
                     f"{{{note}}};")

    # the published scale
    y0 = 3 * (BAR + GAP)
    L.append(f"\\fill[gRule!25] (0,{y0:.2f}) rectangle ({W:.3f},{y0 + BAR:.2f});")
    L.append(f"\\node[anchor=east, gRule] at (-0.12,{y0 + BAR / 2:.2f}) "
             f"{{what the tables publish}};")
    L.append(f"\\node[anchor=west, font=\\scriptsize\\bfseries, gRule] "
             f"at ({W + 0.10:.3f},{y0 + BAR / 2:.2f}) {{{pub}}};")

    # ladder one: a cell must not contradict
    y1 = 2 * (BAR + GAP)
    bar(y1, sign, "gPublished", "no cell contradicts")
    L.append(f"\\node[anchor=west, gPublished!80, font=\\scriptsize\\itshape] "
             f"at (0.12,{y1 + BAR + 0.20:.2f}) {{first reading}};")

    # ladder two: a cell must separate
    y2 = 1 * (BAR + GAP)
    y3 = 0.0
    bar(y2, own, "gReversed", "the board's own cell separates",
        f"{power} never resolved by the benchmark")
    bar(y3, every, "gReversed!70", "every declared cell separates",
        f"{grid} more to the grid of choices")
    L.append(f"\\node[anchor=west, gReversed!85, font=\\scriptsize\\itshape] "
             f"at (0.12,{y2 + BAR + 0.20:.2f}) {{second reading, stricter}};")

    L.append("\\end{tikzpicture}")
    Path(args.out).write_text("\n".join(L) + "\n")

    print(f"  {pub} published places; sign reading {sign}; separation reading {own} then {every}")
    print(f"  attributed: {power} to the benchmark's own power, {grid} to the grid")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
