#!/usr/bin/env python3
r"""The surviving share of every board, drawn, because twenty-three numbers in prose are not read.

The paper's claim is distributional: the part of a published ordering that survives its own grid is
a property of the table rather than a constant of a field. A reader can be told that and will not
believe it from a sentence; the same reader can see it in one strip of dots. So this draws one dot
per leaderboard on a single axis, grouped by domain, with the median marked.

Two things the drawing has to be honest about and the prose can elide. Boards differ enormously in
how many pairs they carry --- three against $171$ --- so the dot area is proportional to the pair
count and a three-pair board cannot look like evidence at a glance. And the two editions of the
translation task are drawn as separate rows rather than pooled, because pooling them would hide the
one comparison in the paper where the same question was put twice to independent data.

Emits TikZ with no external dependency beyond the tikz package the manuscript already loads.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "paper" / "app" / "share_figure.tex"

ROWS = [
    ("retrosynthesis", [("robust_order.json", "cluster0"), ("robust_order.json", "cluster1")]),
    ("metabolites", [("robust_order_metabolite.json", None)]),
    ("docking", [("robust_order_posebusters.json", None)]),
    ("translation, 2024", [("robust_order_wmt24_en-de.json", None),
                           ("robust_order_wmt24_ja-zh.json", None),
                           ("robust_order_wmt24_esa.json", "*")]),
    ("translation, 2023", [("robust_order_wmt23.json", "*")]),
]


def _code_version() -> dict:
    import subprocess

    def _git(*a):
        try:
            return subprocess.run(["git", *a], cwd=ROOT, capture_output=True, text=True,
                                  timeout=10).stdout.strip() or None
        except Exception:
            return None

    return {"script": pathlib.Path(__file__).name, "git_commit": _git("rev-parse", "HEAD")}


def collect() -> list:
    out = []
    for label, sources in ROWS:
        boards = []
        for name, key in sources:
            p = ROOT / "results" / name
            if not p.exists():
                continue
            d = json.loads(p.read_text())
            if key == "*":
                boards += list(d["boards"].values())
            elif key:
                boards.append(d["leaderboards"][key])
            else:
                boards.append(d)
        if boards:
            out.append((label, boards))
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(OUT))
    args = ap.parse_args()

    rows = collect()
    n_boards = sum(len(b) for _, b in rows)
    all_shares = sorted(x["robustness"] for _, b in rows for x in b)
    median = all_shares[len(all_shares) // 2] if len(all_shares) % 2 else \
        0.5 * (all_shares[len(all_shares) // 2 - 1] + all_shares[len(all_shares) // 2])

    W, H = 11.0, 0.28
    lines = ["% generated by scripts/make_share_figure.py -- do not edit by hand",
             "\\begin{tikzpicture}[x=%.4fcm, y=1cm]" % (W,)]
    y = 0.0
    # axis
    lines.append(f"\\draw[gray!45] (0,{-0.30:.2f}) -- (1,{-0.30:.2f});")
    for tick in (0.0, 0.25, 0.5, 0.75, 1.0):
        lines.append(f"\\draw[gray!45] ({tick},{-0.30:.2f}) -- ({tick},{-0.42:.2f});")
        lines.append(f"\\node[below,font=\\scriptsize,inner sep=1pt] at ({tick},{-0.42:.2f}) "
                     f"{{${tick:.2f}$}};")
    lines.append(f"\\draw[dashed,gray!70] ({median:.4f},{-0.30:.2f}) -- "
                 f"({median:.4f},{len(rows) * H + 0.10:.2f});")
    lines.append(f"\\node[above,font=\\scriptsize,gray!70!black] at "
                 f"({median:.4f},{len(rows) * H + 0.06:.2f}) {{median ${median:.2f}$}};")

    for label, boards in reversed(rows):
        y += H
        lines.append(f"\\node[left,font=\\scriptsize] at (-0.012,{y:.2f}) {{{label}}};")
        for b in sorted(boards, key=lambda x: -x["n_pairs"]):
            # area proportional to the pairs the board carries, so a three-pair board cannot
            # look like a hundred-and-seventy-one-pair one
            r = 0.022 + 0.055 * (b["n_pairs"] / 171.0) ** 0.5
            lines.append(f"\\fill[black!62] ({b['robustness']:.4f},{y:.2f}) circle "
                         f"({r:.3f}cm);")
    lines.append("\\end{tikzpicture}")
    Path(args.out).write_text("\n".join(lines) + "\n")

    print(f"  {n_boards} boards drawn, median share {median:.4f}, "
          f"range {min(all_shares):.3f}--{max(all_shares):.3f}")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
