#!/usr/bin/env python3
r"""The surviving share of every board, drawn, because twenty-three numbers in prose are not read.

The paper's claim is distributional: the part of a published ordering that survives its own grid is
a property of the table rather than a constant of a field. A reader can be told that and will not
believe it from a sentence; the same reader can see it in one strip of dots. So this draws one dot
per leaderboard on a single axis, grouped by domain, with the median marked.

Two things the drawing has to be honest about and the prose can elide. Boards differ enormously in
how many pairs they carry --- three against $171$ --- so the dot area is proportional to the pair
count and a three-pair board cannot look like evidence at a glance. And the two editions of the
translation task are drawn as separate rows rather than pooled, because pooling them would hide the
one comparison in the paper where the same question was put twice to independent data.

Emits TikZ with no external dependency beyond the tikz package the manuscript already loads.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "paper" / "app" / "share_figure.tex"

# one colour per domain, named in the manuscript preamble. Hue never carries meaning alone here:
# each domain also has its own row, so the drawing reads the same in greyscale.
COLOUR = {"retrosynthesis": "gPublished", "metabolites": "gMeta", "docking": "gDock",
          "translation, 2024": "gRule", "translation, 2023": "gRule"}

ROWS = [
    ("retrosynthesis", [("robust_order.json", "cluster0"), ("robust_order.json", "cluster1"),
                        ("robust_order_retro_extrapolation.json", "extrapolation50k")]),
    ("metabolites", [("robust_order_metabolite.json", None)]),
    ("docking", [("robust_order_posebusters.json", None)]),
    ("translation, 2024", [("robust_order_wmt24_en-de.json", None),
                           ("robust_order_wmt24_ja-zh.json", None),
                           ("robust_order_wmt24_esa.json", "*")]),
    ("translation, 2023", [("robust_order_wmt23.json", "*")]),
]


def _code_version() -> dict:
    import subprocess

    def _git(*a):
        try:
            return subprocess.run(["git", *a], cwd=ROOT, capture_output=True, text=True,
                                  timeout=10).stdout.strip() or None
        except Exception:
            return None

    return {"script": pathlib.Path(__file__).name, "git_commit": _git("rev-parse", "HEAD")}


def collect() -> list:
    out = []
    for label, sources in ROWS:
        boards = []
        for name, key in sources:
            p = ROOT / "results" / name
            if not p.exists():
                continue
            d = json.loads(p.read_text())
            if key == "*":
                boards += list(d["boards"].values())
            elif key:
                boards.append(d["leaderboards"][key])
            else:
                boards.append(d)
        if boards:
            out.append((label, boards))
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(OUT))
    args = ap.parse_args()

    rows = collect()
    n_boards = sum(len(b) for _, b in rows)
    all_shares = sorted(x["robustness"] for _, b in rows for x in b)
    median = all_shares[len(all_shares) // 2] if len(all_shares) % 2 else \
        0.5 * (all_shares[len(all_shares) // 2 - 1] + all_shares[len(all_shares) // 2])

    # rows a quarter-centimetre apart put five domains inside one centimetre of height, which
    # reads as one cloud of dots rather than five; each row also gets a rule to its own label
    W, H = 11.0, 0.40
    lines = ["% generated by scripts/make_share_figure.py -- do not edit by hand",
             "\\begin{tikzpicture}[x=%.4fcm, y=1cm]" % (W,)]
    y = 0.0
    # axis
    lines.append(f"\\draw[gRule!55] (0,{-0.14:.2f}) -- (1,{-0.14:.2f});")
    for tick in (0.0, 0.25, 0.5, 0.75, 1.0):
        lines.append(f"\\draw[gRule!55] ({tick},{-0.14:.2f}) -- ({tick},{-0.26:.2f});")
        lines.append(f"\\node[below,font=\\scriptsize,gRule,inner sep=1pt] at ({tick},{-0.26:.2f}) "
                     f"{{${tick:.2f}$}};")

    for label, boards in reversed(rows):
        y += H
        col = COLOUR.get(label, "gRule")
        # a band behind each row binds its dots to its label without a rule cutting through them
        lines.append(f"\\fill[{col}!7] (-0.010,{y - H / 2 + 0.03:.2f}) rectangle "
                     f"(1,{y + H / 2 - 0.03:.2f});")
        lines.append(f"\\node[left,font=\\scriptsize,{col}] at (-0.012,{y:.2f}) {{{label}}};")
        for b in sorted(boards, key=lambda x: -x["n_pairs"]):
            # area proportional to the pairs the board carries, so a three-pair board cannot
            # look like a hundred-and-seventy-one-pair one, with a floor so it stays visible
            r = 0.030 + 0.060 * (b["n_pairs"] / 171.0) ** 0.5
            lines.append(f"\\fill[{col}!85, draw=white, line width=0.5pt] "
                         f"({b['robustness']:.4f},{y:.2f}) circle ({r:.3f}cm);")
            # a board where nothing at all survives is the strongest single point on the axis
            if b["robustness"] <= 0.0:
                lines.append(f"\\draw[{col}] ({b['robustness']:.4f},{y:.2f}) circle "
                             f"({r + 0.055:.3f}cm);")
                # a leader from the ring to the label, so the annotation belongs to the dot
                lines.append(f"\\draw[{col}!70,line width=0.3pt] "
                             f"({b['robustness']:.4f},{y + 0.13:.2f}) -- "
                             f"({b['robustness']:.4f},{y + 0.30:.2f}) -- "
                             f"({b['robustness']:.4f}+0.022,{y + 0.30:.2f});")
                lines.append(f"\\node[font=\\scriptsize,{col},anchor=west] at "
                             f"({b['robustness']:.4f}+0.024,{y + 0.30:.2f}) {{nothing survives}};")
    # after the bands and the dots: drawn before them, the opaque fills left this line visible
    # only in the gaps between rows, and its label named a line a reader could not see
    lines.append(f"\\draw[dashed,gRule!60,line width=0.5pt] ({median:.4f},{-0.14:.2f}) -- "
                 f"({median:.4f},{len(rows) * H + 0.26:.2f});")
    lines.append(f"\\node[above,font=\\scriptsize,gRule] at "
                 f"({median:.4f},{len(rows) * H + 0.26:.2f}) {{median ${median:.2f}$}};")
    lines.append("\\end{tikzpicture}")
    Path(args.out).write_text("\n".join(lines) + "\n")

    print(f"  {n_boards} boards drawn, median share {median:.4f}, "
          f"range {min(all_shares):.3f}--{max(all_shares):.3f}")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
