"""Turn the artifact-derived numbers into LaTeX macros the manuscript uses by name.

A number typed into prose can drift from its artifact and did, five times in an hour the last time
prose was written here. A number the manuscript can only reach through a macro cannot: regenerating
this file after a re-run changes the paper, and a stale paper fails to build rather than printing a
stale figure.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))


DIGITS = {"0": "Zero", "1": "One", "2": "Two", "3": "Three", "4": "Four", "5": "Five",
          "6": "Six", "7": "Seven", "8": "Eight", "9": "Nine"}


def name(key: str) -> str:
    """A macro name from a dotted key.

    TeX control sequences take letters only, so every digit is spelled out rather than dropped.
    Dropping them collided h12 with h14 and cap1 with cap2, which the duplicate check caught and
    a reader of the paper would not have.
    """
    words = [w for part in re.split(r"[._]", key)
             for w in re.findall(r"[A-Za-z]+|[0-9]+", part)]
    parts = []
    for w in words:
        if w.isdigit():
            parts.append("".join(DIGITS[c] for c in w))
        else:
            parts.append(w.capitalize())
    return "num" + "".join(parts)


# A share that a table beside it prints as a percentage should not be a bare fraction in the
# prose. The percentage form is generated for every fraction so a sentence can match the table it
# points at without anyone typing the conversion.
def pct(v) -> str:
    s = f"{v * 100:.1f}".rstrip("0").rstrip(".")
    return s + "\\%"


# A difference or an interval bound is quoted beside others to four places, and stripping its
# trailing zeros made one read as "+0.2" next to "+0.2932", which looks truncated rather than
# exact. Differences keep four places; a registered threshold does not, because "0.05" is what
# was registered and "0.0500" is not.
MEASURED = re.compile(r"(?:gap|diff|effect|lo|hi)\d*$")
# A rule index is a name, not a quantity: "template 4,913" is wrong the way "page 1,024" is.
INDEX = re.compile(r"(?:rule|rulehit|deamrule|ruleid|index)$")


def fmt(v, key: str = ""):
    if isinstance(v, bool):
        return "yes" if v else "no"
    if isinstance(v, float):
        if abs(v) < 1 and MEASURED.search(key.split(".")[-1]):
            return f"{v:.4f}"
        s = f"{v:.4f}".rstrip("0").rstrip(".")
        return s if s else "0"
    if isinstance(v, int) and abs(v) >= 1000:
        if INDEX.search(key.split(".")[-1]):
            return str(v)
        return f"{v:,}".replace(",", "{,}")
    return str(v)


# Numerals below ten read badly in a sentence, and the abstract had "under 5 matching criteria
# and 9 output budgets". A word form is generated beside every small whole number so prose can
# reach for it without anyone typing the word, which is the one way it could drift.
# 0 is "none" rather than "no": the word appears as the object of a preposition ("differ in
# none of them"), where "no" is ungrammatical.
WORDS = {0: "none", 1: "one", 2: "two", 3: "three", 4: "four", 5: "five",
         6: "six", 7: "seven", 8: "eight", 9: "nine", 10: "ten", 11: "eleven", 12: "twelve"}


def main() -> int:
    blob = json.loads((ROOT / "results/paper2_numbers.json").read_text())
    nums = blob["numbers"]
    seen, lines = {}, []
    lines.append("% Generated by scripts/paper2_macros.py from results/paper2_numbers.json.")
    lines.append("% Do not edit. A number that is not here may not appear in the manuscript.")
    for k in sorted(nums):
        m = name(k)
        if m in seen:
            raise SystemExit(f"macro collision: {k} and {seen[m]} both give \\{m}")
        seen[m] = k
        lines.append(f"\\newcommand{{\\{m}}}{{{fmt(nums[k], k)}}}  % {k}")
        v = nums[k]
        if isinstance(v, float) and 0.0 <= v <= 1.0:
            share = m + "Pct"
            if share not in seen:
                seen[share] = k + " (as a percentage)"
                lines.append(f"\\newcommand{{\\{share}}}{{{pct(v)}}}  % {k}, as a percentage")
        if isinstance(v, int) and not isinstance(v, bool) and v in WORDS:
            word = m + "Word"
            if word in seen:
                raise SystemExit(f"macro collision on the word form of {k}")
            seen[word] = k + " (word form)"
            lines.append(f"\\newcommand{{\\{word}}}{{{WORDS[v]}}}  % {k}, spelled")
    (ROOT / "paper2" / "numbers.tex").write_text("\n".join(lines) + "\n")
    print(f"wrote paper2/numbers.tex with {len(seen)} macros")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
