#!/usr/bin/env python3
"""The ignore rules say what the repository holds, instead of being overridden 378 times.

`artifacts/`, `results/` and `grail_metabolism/data/` are ignored wholesale because most of what
lands in them is scratch. But the release deposits real artifacts there -- every comparator's
per-substrate predictions, the pools, the checkpoints the paper is measured on -- and each one was
added with `git add -f`. So the rule said one thing, the tree held another, and the only way to
learn which files were deliberate was to ask the index.

That gap is not cosmetic. A reader cloning this repository cannot tell a deposited artifact from a
leftover, `git status` is useless for spotting a new artifact that should be deposited, and every
new one needs a flag that is easy to forget -- which is how a released figure or a comparator's
predictions goes missing from a release that promises it.

This writes the exceptions out, one line per file, generated from what is actually tracked.

    python scripts/sync_tracked_artifacts.py            # rewrite the block
    python scripts/sync_tracked_artifacts.py --check    # non-zero if it is out of date
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
IGNORE = ROOT / ".gitignore"
BEGIN = "# >>> tracked artifacts, generated by scripts/sync_tracked_artifacts.py >>>"
END = "# <<< tracked artifacts <<<"

# The blanket rules whose exceptions this manages. Each is rewritten as a recursive ignore plus a
# re-inclusion of directories, because git will not descend into an excluded directory and a file
# exception under one can never match.
ROOTS = ("results", "artifacts", "grail_metabolism/data")
# Deliverables caught by an extension rule rather than by a directory one, and written into the
# .gitignore that governs them. A nested .gitignore beats the root one for its own tree, so the
# manuscript figures under paper/ cannot be re-included from the root file: nine of them were
# tracked and still reported as ignored until the exceptions moved next to the rule.
NESTED = {"paper/.gitignore": ("paper/", ".pdf")}

# Third-party distributions that live in the working tree and are deliberately not redistributed:
# a comparator's own jar and a comparator's own source checkout, each obtainable from its own
# project. Under the old blanket rule they were invisible; naming them keeps them out of the way
# and keeps the reason written down rather than implied by an absence.
NOT_OURS = {
    "artifacts/tier2/biotransformer/":
        "BioTransformer's distribution: its README requires permission to redistribute, which was "
        "not sought. Obtainable from its own project; paper2/split_manifest.json pins the digest.",
    "artifacts/tier2/metapredictor_src/":
        "MetaPredictor's own source checkout, carrying no licence text this repository can point "
        "at. Obtainable from its own project.",
}


def tracked() -> list:
    out = subprocess.run(["git", "ls-files"], cwd=ROOT, capture_output=True, text=True, check=True)
    return sorted(out.stdout.splitlines())


def block(files: list) -> str:
    lines = [BEGIN,
             "# Every path below is tracked. The rule above each group ignores that tree, these",
             "# re-include exactly what the release deposits, and anything new in those trees stays",
             "# ignored until it is added here. Do not edit by hand: re-run the script.",
             ""]
    for root in ROOTS:
        kept = [f for f in files if f.startswith(root + "/")]
        lines.append(f"{root}/**")
        lines.append(f"!{root}/**/")
        lines += [f"!{f}" for f in kept]
        lines.append(f"#   {len(kept)} tracked under {root}/")
        lines.append("")
    for path, why in sorted(NOT_OURS.items()):
        lines.append(f"# {why}")
        lines.append(path)
        lines.append("")
    lines.append(END)
    return "\n".join(lines) + "\n"


def nested_block(files: list, prefix: str, suffix: str) -> str:
    """The exceptions for one nested .gitignore, which governs its own tree."""
    kept = [f for f in files if f.startswith(prefix) and f.endswith(suffix)
            and "/" not in f[len(prefix):]]
    lines = [BEGIN,
             f"# {len(kept)} tracked {suffix} files under {prefix}, re-included here because a",
             "# nested .gitignore beats the root one for its own tree.",
             ""]
    lines += [f"!{f[len(prefix):]}" for f in kept]
    lines.append(END)
    return "\n".join(lines) + "\n"


def current(text: str) -> str:
    if BEGIN not in text:
        return ""
    start = text.index(BEGIN)
    end = text.index(END, start) + len(END) + 1
    return text[start:end]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    files = tracked()
    want = block(files)
    text = IGNORE.read_text()
    have = current(text)
    nested = {path: nested_block(files, prefix, suffix)
              for path, (prefix, suffix) in NESTED.items()}

    stale_nested = [p for p, w in nested.items()
                    if current((ROOT / p).read_text()) != w]
    if args.check:
        if stale_nested:
            print(f"REFUSING: {', '.join(stale_nested)} does not re-include the tracked files its "
                  f"own rules exclude; re-run scripts/sync_tracked_artifacts.py", file=sys.stderr)
            return 1
        if have != want:
            n = sum(1 for line in want.splitlines() if line.startswith("!"))
            print("REFUSING: .gitignore's tracked-artifact block is not what the index holds. "
                  f"{n} files are tracked inside ignored trees; re-run "
                  "scripts/sync_tracked_artifacts.py", file=sys.stderr)
            return 1
        print(f"the ignore rules match the index: "
              f"{sum(1 for line in want.splitlines() if line.startswith('!'))} deposited artifacts")
        return 0

    # The blanket rules the block replaces are removed, or they would keep winning by position.
    keep = []
    for line in text.splitlines():
        if line.strip() in {f"{r}/" for r in ROOTS}:
            continue
        keep.append(line)
    text = "\n".join(keep) + "\n"
    old = current(text)
    if old:
        text = text.replace(old, want, 1)
    else:
        text = text.rstrip("\n") + "\n\n" + want
    IGNORE.write_text(text)
    for path, w in nested.items():
        f = ROOT / path
        t = f.read_text()
        old_block = current(t)
        f.write_text(t.replace(old_block, w, 1) if old_block else t.rstrip("\n") + "\n\n" + w)
    n = sum(1 for line in want.splitlines() if line.startswith("!"))
    print(f"wrote {n} exceptions for artifacts tracked inside ignored trees")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
